### ISSUE TITLE
We may need to implement the user GUI before we write to pdf...

### ISSUE THREAD

**Issue by Connorapple** [productivityinterns/productivitywebapp#19]
So there is no way to dynamically get the fillable fields and know what they are. When you grab fields they are represented as
```
"f1_01(0)", "1"   
"f1_02(0)", "1" 
"f1_03(0)", "1" 
"f1_04(0)", "8"
```
So, not very helpful and would need a previous knowledge of every document every time it writes.

My thought is that if we build the template creator GUI, complete with the pdf field assigner, we can use that data to "create" our  own pdf which gives us the ability to name and control the fields (im pretty sure at least)

**Comment by S4lt5** [comment]
You could just go with fields in order for the sake of a demo, and have that as one way you can specify them. e.g the 18th field.

But being able to read/write the PDF and give fields names sounds like a good thing, for sure
