### ISSUE TITLE
/Templates/Assign should open a specific form and let the user create assignments for this form

### ISSUE THREAD

**Issue by Connorapple** [productivityinterns/productivitywebapp#40]
Create a method /Templates/Assign that takes the following route params on post
form unique identifer, Assignments[]

![image](https://user-images.githubusercontent.com/7513894/59865650-8a1b6600-9357-11e9-8236-78916f0ba470.png)

This should Generate a list of Assignments that get posted back.

A user will click a field, and be shown the popup window as shown in the mockup that will let the user select a field or criteria.

When the user picks a criteria, the tag of the field should be setup as a new assignment in the pdf.

When the form is submitted, the form id, and the list of Assignments should be posted

On post:
* Find the template related to the form
* Validate the data
* Throw away old assignments for that form
* Save the new ones
* And send the user to /Templates/Assignments page for another form in the template that is not yet filled out. 
  If all are filled out, return the user to the index

**Comment by S4lt5** [comment]
@Connorapple @Tclark26 @Bed3150n I'm out today! I ended up staying late again yesterday to get my other software release out. I'll owrk on the redirect to the right form.

Ben if you get your page stuff up please hit me up here so I know what to merge in, I may take a crack at angular-izing the fields page before monday

**Comment by Bed3150n** [comment]
I committed the delete fields branch, as of right now having a delete for preexisting fields is a bit redundant because all fields are template fields, but letting @Yablargo know its up

**Comment by S4lt5** [comment]
This more or less in place, but criteria don't show up in the dropdown yet
